"use client";

import { useSearchParams } from "next/navigation";
import { useState, Suspense } from "react";
import { authClient } from "@/lib/auth-client";

function DeviceCodeContent() {
  const searchParams = useSearchParams();
  const initialCode = searchParams.get("user_code") || "";
  const [userCode, setUserCode] = useState(initialCode);
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setIsLoading(true);

    try {
      const formattedCode = userCode.trim().replace(/-/g, "").toUpperCase();

      if (!formattedCode) {
        setError("Please enter a device code.");
        setIsLoading(false);
        return;
      }

      const response = await authClient.device({
        query: { user_code: formattedCode },
      });

      if (response.data) {
        window.location.href = `/device/approve?user_code=${encodeURIComponent(formattedCode)}`;
      } else {
        setError("Invalid or expired code. Please try again.");
      }
    } catch {
      setError("Invalid or expired code. Please check and try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="max-w-md mx-auto">
      <div className="bg-white rounded-2xl shadow-lg p-8">
        <div className="text-center mb-6">
          <div className="inline-flex items-center justify-center w-12 h-12 rounded-full bg-pana-50 mb-4">
            <svg
              className="w-6 h-6 text-pana-500"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
              />
            </svg>
          </div>
          <h2 className="text-2xl font-semibold text-gray-900 mb-2">
            Device Authorization
          </h2>
          <p className="text-gray-600 text-sm">
            Enter the code displayed on your CLI to authorize the device.
          </p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label
              htmlFor="device-code"
              className="block text-sm font-medium text-gray-700 mb-1"
            >
              Device Code
            </label>
            <input
              id="device-code"
              type="text"
              value={userCode}
              onChange={(e) => setUserCode(e.target.value)}
              placeholder="e.g., ABCD-1234"
              maxLength={12}
              autoFocus
              autoComplete="off"
              className="w-full px-4 py-3 text-center text-lg font-mono tracking-widest border border-gray-300 rounded-lg focus:ring-2 focus:ring-pana-500 focus:border-pana-500 outline-none uppercase"
            />
          </div>

          {error && (
            <div className="bg-red-50 border border-red-200 rounded-lg p-3">
              <p className="text-sm text-red-700">{error}</p>
            </div>
          )}

          <button
            type="submit"
            disabled={isLoading || !userCode.trim()}
            className="w-full py-3 px-4 border border-transparent rounded-lg text-sm font-medium text-white bg-pana-500 hover:bg-pana-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-pana-500 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            {isLoading ? "Verifying..." : "Continue"}
          </button>
        </form>

        <p className="text-xs text-gray-500 text-center mt-6">
          This code was generated by a CLI application requesting access to your
          account.
        </p>
      </div>
    </div>
  );
}

export default function DevicePage() {
  return (
    <Suspense
      fallback={
        <div className="flex items-center justify-center py-8">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-pana-500"></div>
        </div>
      }
    >
      <DeviceCodeContent />
    </Suspense>
  );
}
